### ISSUE TITLE
Return OpenAttemptedDuringTransaction when open store with create=false

### ISSUE THREAD

**Issue by chinuno-usami** [mozilla/rkv#138]
It could be reproduce by modify example/simple-store.rs.
At https://github.com/mozilla/rkv/blob/master/examples/simple-store.rs#L102 to  
```rust
let reader = k.read().unwrap();
let mut opt = StoreOptions::create();
opt.create = false;
let store2 = k.open_single("store", opt).unwrap();
println!("Get int {:?}", store2.get(&reader, "int").unwrap());
println!("Get uint {:?}", store2.get(&reader, "uint").unwrap());
println!("Get float {:?}", store2.get(&reader, "float").unwrap());
println!("Get instant {:?}", store2.get(&reader, "instant").unwrap());
println!("Get boolean {:?}", store2.get(&reader, "boolean").unwrap());
println!("Get string {:?}", store2.get(&reader, "string").unwrap());
println!("Get json {:?}", store2.get(&reader, "json").unwrap());
println!("Get blob {:?}", store2.get(&reader, "blob").unwrap());
println!("Get non-existent {:?}", store2.get(&reader, "non-existent").unwrap());
```
It works fine when I set `opt.create = true`.But panic when `opt.create = false`.
Shows 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OpenAttemptedDuringTransaction(ThreadId(1))', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/3991285f55a4b7cd92b7ffcdc396a3023076f5cb/src/libcore/macros.rs:18
   9: core::result::Result<T,E>::unwrap
             at /rustc/3991285f55a4b7cd92b7ffcdc396a3023076f5cb/src/libcore/result.rs:800
  10: simple_store::main
             at examples/simple-store.rs:104
```
Or did I use the Option wrong way?

Toolchains :`rustc 1.36.0-nightly (3991285f5 2019-04-25)`
OS:`Ubuntu kernel Linux 4.15.0`

**Comment by ncloudioj** [comment]
Looks like the error was caused by attempting to open a non-existed store.

If you're not sure about whether that store has been created or not, you can just use the default `StoreOption`, which will create the store if necessary, otherwise, it'll simply open it. Setting `create` to false only if you're sure that store already exists.

**Comment by chinuno-usami** [comment]
I am sure that store already exists.
It has put some data at https://github.com/mozilla/rkv/blob/master/examples/simple-store.rs#L68 .
So the "store" store should has been created before https://github.com/mozilla/rkv/blob/master/examples/simple-store.rs#L102

**Comment by ncloudioj** [comment]
Open the same store twice from one thread will fail with this error. Is there any `open_single()` before this one in your example?

**Comment by chinuno-usami** [comment]
I do open the store twice. It seems to be the reason why returns error. But it works well when I open the store with `create=true` at the second time.
Should I make the opened store a global variable if I encapsulate all rkv operations into a module？

**Comment by ncloudioj** [comment]
Sure, you can keep the store open if it will be frequently used. Under the hood, it's a just handle to the underlying LMDB database.

Just make sure don't open it more than once on the same thread, because each store is opened with an implicite transaction, which internally creates a slot in the LMDB reader table associated with the current thread. When attempting to open the that store again from the same thread will fail with `MDB_BAD_SLOT`, which in turn triggers the `OpenAttemptedDuringTransaction` here.

**Comment by chinuno-usami** [comment]
Thank you for your reply. It helps a lot.
