### ISSUE TITLE
Build non-nightly

### ISSUE THREAD

**Issue by flipchan** [mozilla/rkv#147]
Hey, 
Is there a way of building it without cargo +nightly build?
0.9. 4-5 just compiles nightly

**Comment by mykmelez** [comment]
Sorry for the delay responding! However, I don't experience a problem build 0.9.4, 0.9.5, or the current tip of the master branch with the current stable release of Rust (which for me right now is `rustc 1.36.0 (a53f9df32 2019-07-03)`). Can you describe the problem you're seeing in more detail?

**Comment by eftychis** [comment]
I don't have an issue building 0.9.7 with 1.36 (rustc version 1.36.0 (a53f9df32 2019-07-03) either.

**Comment by victorporof** [comment]
We're building on nightly in CI and everything should be working just fine. Closing this.
