### ISSUE TITLE
Implement closing of stores via Manager

### ISSUE THREAD

**Issue by rnewman** [mozilla/rkv#191]
If an `Arc` has a refcount of 1, nobody else is using the store. It should be possible to (a) close a named store if it is otherwise unreferenced, and (b) close all stores that are otherwise unreferenced.

This is a prerequisite for some long-running uses of rkv.

**Comment by victorporof** [comment]
Yes, this should be easily doable. PRs welcome.

**Comment by victorporof** [comment]
Actually, I've already implemented this recently. See https://github.com/mozilla/rkv/blob/master/src/manager.rs#L156
