### ISSUE TITLE
Incorrect description about reading the uncommitted writes in the same transaction

### ISSUE THREAD

**Issue by ncloudioj** [mozilla/rkv#54]
> A write transaction also supports reading, but the version of the store that it reads doesn't include changes it has made.

This seems not correct, at least running the code snippets shows the opposite result. Within the same write transaction, all the writes should be immediately visible regardless of the commit state of that transaction.

Thanks @piatra for pointing out this by noticing the discrepancy between the document and the actual code result!

**Comment by mykmelez** [comment]
Indeed! This is fixed by @piatra's #55. I wonder if we should change all the println! calls to assertions in order to ensure that tests fail under such circumstances.
