### ISSUE TITLE
integrate clippy in some fashion

### ISSUE THREAD

**Issue by mykmelez** [mozilla/rkv#68]
Over in #65, @ncloudioj fixed some clippy nits. We should consider integrating clippy in some fashion to reduce the risk of introducing more such nits.

Per https://github.com/rust-lang-nursery/rust-clippy, "Since this is a tool for helping the developer of a library or application write better code, it is recommended not to include Clippy as a hard dependency. Options include using it as an optional dependency, as a cargo subcommand, or as an included feature during build. These options are detailed below."

I'm unsure which of these options is best.

**Comment by ncloudioj** [comment]
Also new to clippy here. I've seen some projects leveraging clippy as the "dev" feature during build (I guess the latter above?). Perhaps we can try the same?
